### ISSUE TITLE
How to validate hidden select box

### ISSUE THREAD

**Issue by pauldcollins** [atetlaw/Really-Easy-Field-Validation#4]
Hi, thanks for the great plugin!

I'm trying to validate a select box that is replaced with DIVs using the chosen plugin.
https://github.com/harvesthq/chosen/

The plugin hides the select box using "display:none", so I can override with CSS "display:block", but I was just wondering if there's a more elegant way of validating the hidden select within the JS for the plugin?

Thanks for any help.

**Comment by atetlaw** [comment]
Your best bet would be to write a custom validator function. I assume that the plugin has an API for getting and setting the select value, you could use that.

**Comment by pauldcollins** [comment]
OK, thanks for your reply @atetlaw - I will do that!

Cheers
